services:
  # 1. Backend and blockchain listener
  - type: web
    name: verdict-backend
    runtime: python
    rootDir: backend        # The server told us to log into the Backend folder to work
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"

  # 2. Static frontend interface (React + Vite)
  - type: web
    name: verdict-frontend
    runtime: static
    rootDir: frontend       # The server told us to log into the frontend folder to work
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist # The volume became relatively for frontend
